# Generated by Django 4.1.13 on 2023-12-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0003_carts_isfinished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='isFinished',
            new_name='is_finished',
        ),
    ]
