# Generated by Django 4.1.13 on 2023-12-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0004_rename_isfinished_carts_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.FloatField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramdeals.carts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramdeals.producto')),
            ],
        ),
    ]
