# Generated by Django 4.1.13 on 2023-12-01 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ramdeals', '0005_cartsitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.FloatField()),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ramdeals.producto')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
