# Generated by Django 4.1.13 on 2023-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0013_alter_producto_final_price'),
    ]

    operations = [
    ]
