# Generated by Django 4.1.13 on 2023-12-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0014_remove_producto_final_price_and_more'),
    ]

    operations = [
    ]
