# Generated by Django 4.1.13 on 2023-12-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0015_rename_price_discounted_producto_final_price'),
    ]

    operations = [
    ]
