# Generated by Django 4.1.13 on 2023-12-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0016_remove_producto_final_price'),
    ]

    operations = [
    ]
