# Generated by Django 4.1.13 on 2023-12-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0017_popo'),
    ]

    operations = [
    ]
