# Generated by Django 4.1.13 on 2023-12-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0018_delete_popo_producto_final_price'),
    ]

    operations = [
    ]
