# Generated by Django 4.1.13 on 2023-12-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0019_remove_producto_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='final_price',
            field=models.FloatField(default=0.0),
        ),
    ]
