# Generated by Django 4.1.13 on 2023-12-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramdeals', '0020_producto_final_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
